// -----------------------------------------------
// This server is not run by webpack. Instead,
// this server is to run public folder generated by
// $ yarn run build:prod
//
// Thus, this server is run via command line
// $ node server/server.js
//
// -----------------------------------------------

const path = require("path");
const express = require("express");
const app = express();

const publicPath = path.join(__dirname, "..", "public");
const port = process.env.PORT || 3000;

app.use(express.static(publicPath));

app.get("*", (req, res) => {
	res.sendFile(path.join(publicPath, "index.html"));
});

app.listen(port, () => {
	console.log("Server is up!");
});
